version: '3.7'

services:
  microblog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microblog
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: ["bash", "boot.sh"]